# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib(num_terms=None, highest_term=None):
    a, b = 1, 2

    if num_terms is not None and highest_term is not None:
        print("Enter either num_terms or highest_term, not both")
    elif num_terms is None and highest_term is None:
        print("Enter either num_terms or highest_term")
    elif num_terms is not None:
        for _ in range(num_terms):
            yield a
            a, b = b, a + b
    elif highest_term is not None:
        while a <= highest_term:
            yield a
            a, b = b, a + b


if __name__ == '__main__':
    print(sum([i for i in list(fib(highest_term=4000000)) if i % 2 == 0]))
